// SEO details
export const FETCH_PROJECT_DETAIL_SUCCESS = 'FETCH_PROJECT_DETAIL_SUCCESS';
export const FETCH_PROJECT_DETAIL_FAIL = 'FETCH_PROJECT_DETAIL_FAIL';

// Users
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAIL = 'FETCH_USER_LIST_FAIL';